### ISSUE TITLE
Not finding all fluids.

### ISSUE THREAD

**Issue by brisingraerowing** [DoctorFTB/FluidCows#1]
I have this installed along with a number of other mods with fluids, and many of them (All Tinkers fluids, stuff from Immersive Petroleum, and so on) are not being found by this mod. Moo Fluids also has the same issue, so I think it may have to do with load order, though messing with the mod names in the Twitch Launcher causes headaches.

**Comment by DoctorFTB** [comment]
Hi. 
Could you say mod(s) without support?
-Thanks.

**Comment by brisingraerowing** [comment]
Tinkers Construct, PlusTiC, Immersive Petroleum, Industrial Foregoing.

The output when creating the config file says that there's only 21 fluids at that time, even though I have many more.

EDIT: I'm testing whether renaming the file to load last will fix this.

**Comment by DoctorFTB** [comment]
Ok, working on it.

**Comment by brisingraerowing** [comment]
The test failed (it still said 21 fluids).

**Comment by DoctorFTB** [comment]
I fix in next version.
After I upload next version to Curse - I write here.

**Comment by brisingraerowing** [comment]
Sounds good to me.

**Comment by DoctorFTB** [comment]
Try 1.0.1 version after approved on CurseForge.

**Comment by DoctorFTB** [comment]
@BrisingrAerowing

**Comment by brisingraerowing** [comment]
Having issues starting the game for no reason. Still trying to figure that out.

**Comment by brisingraerowing** [comment]
Got the game loaded. It seems to be working correctly now.
