### ISSUE TITLE
Fluid cows in Stalls causing dramatic FPS loss

### ISSUE THREAD

**Issue by M4xiNus** [DoctorFTB/FluidCows#11]
Currently running 1.1.8 Version
System Specs : 
CPU: AMD Ryzen 7 1700x
RAM : 16GB DDR4 Corsair Vengance(6 allocated to client 8 to server 2 free)
GPU: Nvidia GTX 970
The Issue is that on what seems to be a random per cow issue , and only when in their stalls, if you try to pipe the fluids out your frame rates just plummet. I've been able to replicate it on several cows and at first I thought it was Tinkers Construct casting Basins but alas i was sadly wrong. then when i just started removing cows the lag vanished. put the same cow in boom lag. so as a temp fix I've just removed the troubled cows and I have tried replacing the stalls and piping , as well as different pipes from different mods, same result. I've also tried deleting the trouble cows and spawning replacements in to have the same effect. I've also tried Reloading the Chunks manually also fruitless. Normally i'd chalk it up to just a bug with the stalls but its not all of them, I think that's the weirdest bit. As for the pipes im using Its Ender IO's Ender fluid pipes then into a Tinkers Basin hoppered out into barrels, as a temp thing i don't have an ME yet stop judging me. I really like this mod Especially for things like Stone block hopefully this gives you something to look at and it helps, I've only had it happen with about 10ish cows give or take.

Anyways Cheers 

-MaxiNus_

**Comment by zedekblue** [comment]
Also having this issue. Proof of the dramatic FPS drop just 1 random cow can give: 
![2019-02-01_10 43 40](https://user-images.githubusercontent.com/17040113/52097611-1d553880-260f-11e9-801d-0d0b0a0921ba.png)
![2019-02-01_10 44 09](https://user-images.githubusercontent.com/17040113/52097612-1d553880-260f-11e9-9977-ed4eb97aea43.png)
60 -> 14/16 with just 1 additional cow.
Tried a few different layouts to reduce lag, but all of them still produce this issue.  
Will continue to test over the next few days, as I'd really like to get this fluid system set up somehow...
Edit: Chunk updates also go from 5/10 -> 16/30. This system is across 2 chunkloaded chunks.

**Comment by DoctorFTB** [comment]
I added in todo hiding render cow in stall.

**Comment by DoctorFTB** [comment]
Try 1.1.16 version.
In config: category "Client" -> "HideFluidLayerCow" -> set to true.

**Comment by zedekblue** [comment]
They are just being rendered as normal cows now...
This is on ftb stoneblock v 1.4.0.

![2019-02-10_15 27 26](https://user-images.githubusercontent.com/17040113/52530407-7e37eb80-2d48-11e9-9450-4bc5c0d9fa38.png)

**Comment by DoctorFTB** [comment]
Oh.. Disable fluid layers not fix problem..
Could u join to discord and write me in DM, I send private version without register render for tests?
Because I not want test version to Curse.

**Comment by ttechr** [comment]
I too am having this same issue on my server. Had to move all my cows to a compact room to alleviate the drop for now.

**Comment by Cloudhunter** [comment]
I believe #11 and #13 may have the same root cause - as you can see at the top left, there are a lot of chunk updates which would result in the chunk being rebuilt constantly to render which would lower FPS as this is done in the render thread.
![image](https://user-images.githubusercontent.com/1624192/53117783-93302e00-3543-11e9-81c0-af5e94cd23bf.png)

**Comment by DoctorFTB** [comment]
Try 1.1.17 version. I think this fixed.

**Comment by DoctorFTB** [comment]
Closed. In code: fixed. Not tested because TS not send any answer.
