### ISSUE TITLE
Breeding Problem

### ISSUE THREAD

**Issue by TheError007** [DoctorFTB/FluidCows#12]
Hello!
I've got a little problem. Whenever i try to breed cows, for example Molten Dark Steel cow with Obsidian cow. I gave them wheat, Particles poped up(they ate the wheat) and nothing happend. With both having Breeding Time: Ready after i gave them the wheat.

Is there any condition in order to breed? Like have specific are or light level?

**Comment by DoctorFTB** [comment]
Do u have recipe "Dark Steel" + "Obsidian" = "???".
If u not have recipe - u not have any babies.

U can breeding only:
If cows have same fluids.
If cows have breeding result.

**Comment by DoctorFTB** [comment]
Closed. Because author not send any other info. (Or question solved)
