### ISSUE TITLE
Severe network traffic caused by Cow Stall with occupant.

### ISSUE THREAD

**Issue by NoxyNixie** [DoctorFTB/FluidCows#13]
I've noticed some severe network traffic cause by the cow stalls. A simple test shows me an increase of roughly `~ 0.036` Mbps per stall.

Minecraft total transfer rate `~ 0.055 Mbps`:

![](http://cyanox.nl/sc/javaw_2019-02-07_01-32-48.png)

Minecraft total transfer rate `~ 0.127 Mbps`:

![](http://cyanox.nl/sc/javaw_2019-02-07_01-33-30.png)

Minecraft total transfer rate `~ 6.2 Mbps`:

![](http://cyanox.nl/sc/javaw_2019-02-07_01-40-05.png)

This last screenshot has 168 stalls all occupied (which in turn points to roughly 0.036 Mbps per stall).

This amount of traffic is ludicrous for cows that only produce a bucket of fluid once every 4 hours.

**Comment by DoctorFTB** [comment]
Try 1.1.16 version.

**Comment by DoctorFTB** [comment]
@CyaNox

**Comment by Cloudhunter** [comment]
I confirm I am seeing similar issues on the 1.1.16 version. It appears from the Tile Entity code that you are marking the block as dirty every 10 ticks of the cooldown time - which would result in the entire tile entity being sent and potentially the entire chunk.

If you do wish to update the cooldowns on the client on a constant basis, may I recommend you do it less frequently and decrement the variable on the client instead - and perhaps use a custom packet to avoid sending everything and causing a block update?

**Comment by DoctorFTB** [comment]
Try 1.1.17 version. I think this fixed.

**Comment by DoctorFTB** [comment]
Closed. In code: fixed. Not tested because TS not send any answer.
