### ISSUE TITLE
Feature Request? Dimensional Blocking

### ISSUE THREAD

**Issue by Leftorius** [DoctorFTB/FluidCows#16]
Is there already a method of disabling "Overworld Spawn" other than blacklisting all overworld biomes? 
Can you implement a method of disabling spawn in certain dimensions?

**Comment by DoctorFTB** [comment]
Added in dev.
After finish release # 17 - I upload version to Curse.

**Comment by DoctorFTB** [comment]
Try 1.1.18 version.

**Comment by DoctorFTB** [comment]
Closed. In code: added. Not tested because TS not send any answer.

**Comment by Xenimus0** [comment]
The dimension Blacklist doesn't work. Fluid cows still spawn in dimensions added to the blacklist.
