### ISSUE TITLE
Feature requests to make breeding cows less grindy and storage less cumbersome

### ISSUE THREAD

**Issue by pnieuwkamp** [DoctorFTB/FluidCows#17]
Hi, I love the mod, but breeding cows is a bit of a hassle, and therefor I have two proposals:

First the halter. The only way to know what kind of cow you're handling is by hovering over the halter with the mouse. When you have a crate full of halters, this gets old FAST. My proposal is to make it possible for the halter drop the cow as an item (as a separate mode of the halter, or maybe as separate tool). This resets both times, next usage and breeding time. 
"Next usage" timer: I don't care while breeding. After that, if I do care (often I still don't), I can use the 'regular' mode of the halter (or a golden lasso or soul vial) to transport cows.
"Breeding time" timer: Yes, the way this works now means this can be abused. Therefor I propose to change that so the breeding timer is also reset. The craftable cows have a breeding timer of 5 minutes so that's not a big problem, and for the others it's up to the player to decide if they want the logistic hassle of halters, with an intact breeding timer, or the logistic ease of cow-items with a breeding timer hassle. We don't have access to the higher tier cow items anyway (outside of cheating or creative) so a change in behavior should not be a problem?

Next: Baby cows. Would it be possible to add a block that teleports baby cows from front to back (to separate them from the adults) like the Industrial Foregoing Animal Baby Separator, but with a white- or blacklist? Right now I have a pen with  an Automatic Feeder and a Baby Separator putting the babies in a second pen, but when I come back after half an hour or an hour I the baby pen has a lot of different cows (for instance 10 Destabilized Redstone cows, 11 Silver cows and 2 Energetic Silver cows). It would be nice to have a way to automatically separate them, even opening up whole new ways of automation.

**Comment by DoctorFTB** [comment]
Hi.
Requests accepted, added in todo:
Item which add transform Fluid Cow to "Cow Displayer" (in new version is "Fluid Cow (Name)".
Fluid Cow sorter with config "Baby/Adult" and with selecting fluids (max I think ?9?).
And.. I think add Fluid Cow Feeder (for collection :D)

**Comment by pnieuwkamp** [comment]
Max 9 should be plenty, otherwise just place more of them, or don't have so many different cows breeding next to the same sorter.

A Cow Feeder sounds nice, keep it all in the same mod :)

**Comment by DoctorFTB** [comment]
Soo..
Transform cow -> displayer added.
Working on feeder & sorter.
~
About slots.. Feeder have 3 slots for wheat, sorter have 9 fluid filter slots.

**Comment by pnieuwkamp** [comment]
Nice.

How do we operate the filter? A common method is having to drag a bucket with fluid to a slot, which should be doable for the parents, but you may not have the fluid of the cow you're trying to get yet. Could you make it so we get to choose between a blacklist and a whitelist? Move all babies that match the filter, or move all babies that do not match the filter?

Unfortunately I wouldn't know where to start or I'd offer to help...

**Comment by DoctorFTB** [comment]
Sorry for waiting.. More one week I search who can make textures..

Try 1.1.18 version.

**Comment by DoctorFTB** [comment]
Closed. In code: added. Not tested because TS not send any answer.
