### ISSUE TITLE
These fluid cows look bad when the shader is running.

### ISSUE THREAD

**Issue by Xinmudotmoe** [DoctorFTB/FluidCows#19]
ModVersion:1.1.17
phenomenon:
![2019-04-29_09 50 49](https://user-images.githubusercontent.com/13375525/56889680-9b5b9b00-6aa9-11e9-83ca-6893434a1e9b.png)

**Comment by DoctorFTB** [comment]
What mod u use?

**Comment by Xinmudotmoe** [comment]
Optifine_1.12.2_HD_U_E3, FluidCows-1.1.17,and some unrelated mod.

Optifine can modify the lighting and lighting of this game. 

I have 5 shaderpacks, but both have this problem.

**Comment by DoctorFTB** [comment]
What mod u use for shaders?

**Comment by Xinmudotmoe** [comment]
shader:["BSL+Extreme+v4","KUDA-Shaders v6.1 Legacy","PlunderPixels_Shaders_1.7.x","SEUS-Renewed-1.0.0","Wisdom-Shaders-V3.2-Release-Build3230"]

mod:[minecraft@1.12.2,FML@8.0.99.99,forge@14.23.5.2811,fluidcows@1.1.17,mcp@9.42,ftblib@5.4.1.94]

Now in effect:SEUS-Renewed-1.0.0

**Comment by DoctorFTB** [comment]
Working on fix.

**Comment by Xinmudotmoe** [comment]
Yes, it works.

**Comment by DoctorFTB** [comment]
Whaaat?

**Comment by Xinmudotmoe** [comment]
Sorry, I was busy recently and couldn't see your reply.

Wow, it's normal. Thank you very much!

**Comment by DoctorFTB** [comment]
But I didn't do anything..

**Comment by Xinmudotmoe** [comment]
I downloaded the new version of Mod. Now, That is the 1.1.19 version.

It is now normal when using "Wisdom-Shaders-V3.2-Release-Build3230".

![2019-05-26_17 49 27](https://user-images.githubusercontent.com/13375525/58380072-e6040080-7fde-11e9-9d06-87f718548478.png)

Wait, it seems that this problem still exists when using SEUS-Renewed-1.0.0.

Emmm, I don't seem to have enough tests. I am stupid.
