### ISSUE TITLE
Request - Support for Super Blocks by Wabbity

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [DoctorFTB/FluidCows#2]
So no matter which way I try and make it work I cannot suckle cows with a super bucket a little help please :D

**Comment by DoctorFTB** [comment]
Mod "superblocks" not have correct support to other mods.
Support need add in "superblocks" mod, no in my.

**Comment by P3rf3ctXZer0** [comment]
Understood I will pass the message.
