### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by krisjenner** [DoctorFTB/FluidCows#20]
Crash when creating Fluid Cow spawner (Stoneblock 2)

[crash](https://gist.github.com/krisjenner/6349a5e3b0c4d38e2345acf9fb5fc313)

[log](https://gist.github.com/krisjenner/1e45f65efeb66281a543e145984d7cc7)

**Comment by DoctorFTB** [comment]
What fluid name u want spawn?

**Comment by DoctorFTB** [comment]
Try 1.1.19 version.

**Comment by DoctorFTB** [comment]
Closed. In code: fixed. Not tested because TS not send any answer.
