### ISSUE TITLE
Just a question about spawn rates

### ISSUE THREAD

**Issue by makiharukawa** [DoctorFTB/FluidCows#23]
Hate to ask something so stupid, but im a bit overwhelmed with the config file. I want to make the overall spawning of fluid cows much rarer, which setting should i adjust?

**Comment by DoctorFTB** [comment]
Change this config:
"FluidCowsSpawnWeight" = Fluid cows spawn weight
"FluidCowsSpawnMin" = Fluid cows spawn min
"FluidCowsSpawnMax" = Fluid cows spawn max

I think weight = 1, min = 1, max = 1 -> so rare cows.

**Comment by DoctorFTB** [comment]
@makiharukawa Any other problems?
