### ISSUE TITLE
Completely disable fluids from mods

### ISSUE THREAD

**Issue by darkfr3ak** [DoctorFTB/FluidCows#24]
could you add a possibility to disable cows from certain mods like Nuclearcraft, Animania and so on completely? Right now i have to know which fluid is from these mods to disable them.

**Comment by DoctorFTB** [comment]
For get all fluids from mod - install only two (with mod libs) mods: Fluid Cows & mod.

**Comment by darkfr3ak** [comment]
Good idea, thanks :) But then there is another problem: For example i want to disable all fluids from Nuclearcraft. That's a huge list and because the fluidcows_v2.json from my main modpack is unstructured, i have to search the whole file for every fluid that i want to disable. isn't there an easier way?

**Comment by DoctorFTB** [comment]
If you NOT configure other fluids:
You can install mods & Fluid Cows, start MC, stop MC, open file and replace all `"enabled": true` to `"enabled": false`, after copy config to pack with all mods, start MC and you have config with disabled cows from "bad" mods and enabled cows from other mods.

**Comment by DoctorFTB** [comment]
Question solved? Any other questions?
