### ISSUE TITLE
Feeder

### ISSUE THREAD

**Issue by vFoxyy** [DoctorFTB/FluidCows#26]
Hi, I have done some research and cannot find anything explaining exactly how the feeder works, my main question is "Is the feeder smart in a way that it will breed cows to progress? and not just keep breeding randoms cows?"

Thanks.

**Comment by DoctorFTB** [comment]
Feeder get all cows from radius.
Check all cows can mate with other cows.
If it can, check wheat count > 2.
And after start breeding two cows.

Its work same cows and with different cows which can breeding.
