### ISSUE TITLE
Growth Accelerator

### ISSUE THREAD

**Issue by Tinkertee** [DoctorFTB/FluidCows#28]
Hello, having an issue with the Growth Accelerator. What is the liquid portion and how exactly does one use it. All I have figured out if that you can place wheat into it and it feeds baby cows.

**Comment by DoctorFTB** [comment]
You can insert water for get more substance from wheat.

**Comment by Tinkertee** [comment]
Also is there any way to bypass the 5 minute breeding timer?

**Comment by DoctorFTB** [comment]
Soo.. I think no.
