### ISSUE TITLE
Mekanism Fluid Cows

### ISSUE THREAD

**Issue by Darkkender** [DoctorFTB/FluidCows#29]
Is there any plans to implement Fluid Cows that produce the Mekanism fluids?  Currently there are cows that produce Brine, Water, Heavy Water, & Liquid Lithium that are available to use in Mekanism.  However the following liquids are not available to use in Mekanism, Hydrogen, Oxygen, Chlorine, Sulfur Dioxide, Sulfur Trioxide, Sulfuric Acid, Hydrogen Chloride, Ethylene, Sodium, Deuterium, Tritium, & D-T Fuel.  I'm not sure how many others have wanted to use these same fluids from the cows from Mekanism and haven't been able too.  It would certainly make 5 times ore duplication easier to get too.

**Comment by DoctorFTB** [comment]
I think all not available fluids from Mekanism are/is gas.
Try move fluids via EnderIO fluid conduit.
If u can move - its fluids and I go check if its error from mod.
If u cant move - its gas and mod not supported gas.

**Comment by Darkkender** [comment]
So prior to posting I had actually tried different fluid pipes.  The fluids
go in but they do not transfer into Mekanism machines that are looking for
the Mekanism specific fluids.  For example the Mekanism machine "Rotary
Condensentrator" accepts a fluid and can output a gas & visa versa it can
convert a gas to a fluid but it will only do so with the Mekanism fluids
excluding Water.  Many of the fluids I mentioned are both in Nuclearcraft
and Mekanism however I believe they have a different ID much like you run
into with multiple ore mods.  I don't think anyone has focused on fluids
for the various combined id in oredictionary.

**Comment by DoctorFTB** [comment]
Oh..
Mekanism fluids not have variant with bucket.
Mod not support fluids which not have variant with bucket.

**Comment by Darkkender** [comment]
Alright that makes sense from that perspective.

**Comment by DoctorFTB** [comment]
And if I add all fluids, player say WTF, I cant puckup fluid from stall. Because fluid not have variant with bucket.
