### ISSUE TITLE
Cows spawning naturally with "spawnrate" set to 0

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [DoctorFTB/FluidCows#4]
This is in the Stoneblock 2 modpack, haven't touched the config yet players have had cows naturally spawn even when the config file says they have a 0 spawn rate.

**Comment by DoctorFTB** [comment]
What type of cow? Fluid cows or vanilla cows?
If fluid cows:
Could u send cfg file (mc/config/fluidcows_v2.json) and what type cow spawned?
If not fluid cows:
Vanilla cows can spawn. Its not added by mod.

**Comment by nzminecraftDOTcom** [comment]
The cows that spawned? Fluid cows because that's why I posted the issue. Someone had an Infinity cow spawn apparently after a few others had fluid type had already spawned.

**Comment by DoctorFTB** [comment]
Do u use spigot?
Could u send cfg file (mc/config/fluidcows_v2.json) ?
Infinity cow spawned by natural spawn?

**Comment by nzminecraftDOTcom** [comment]
Fairly certain, they said it was their "5th natural spawned fluid cow"

[fluidcows_v2.txt](https://github.com/DoctorFTB/FluidCows/files/2738281/fluidcows_v2.txt)
Had to rename it to .txt to upload it here.
Spongeforge, not spigot.

**Comment by DoctorFTB** [comment]
Check in console "This is info! Support ... fluids. Can spawn ... cows.". What numbes in "..." in log?
And try without Spongforge.

**Comment by nzminecraftDOTcom** [comment]
[03:03:30] [Server thread/INFO] [fluidcows]: [FluidCows] This is info! Support 177 fluids. Can spawn 0 cows.

Spongeforge is the servers backbone and would break multiple things and with more than 20 players on at all times I won't be removing it sorry.

**Comment by DoctorFTB** [comment]
Ok. "Can spawn 0 cows."
Not really spawn any fluid cows by natural spawn.
Option with natural spawn activated only if 1 or more cows can spawn.
~
I think its Sponge bug.
Because if use only Forge - no problems with spawn.

**Comment by nzminecraftDOTcom** [comment]
Righto, might have to make a test server to see whats happening. Also while I have your attention, is there anything in game that speeds up their growth, like vanilla has for mobs e.g feed chicken seeds and it grows from a baby to an adult faster

**Comment by DoctorFTB** [comment]
Check breedingItemWork in config.
If true - u can speed up with wheat.
If false - only wait.
By default - false

**Comment by nzminecraftDOTcom** [comment]
Awesome, thanks for your help!
