### ISSUE TITLE
Texture not corresponding to the actual fluid

### ISSUE THREAD

**Issue by Todomir** [DoctorFTB/FluidCows#5]
I've had this problem where the cow's texture doesn't correspond to it's actual fluid, and everytime I get one inside the Cow Halter is that it shows the true fluid, once is out it seems it picks a different type of cow. 
E.g. a molter terrasteel cow, once inside the halter, turns into a lava cow. If it is released again, it turns into a molten obsidian cow and once it's back in the halter, it becomes a lava cow again.

**Comment by DoctorFTB** [comment]
Could u make video with that ?
And could u try with only Fluid Cows mod, it will work ?

**Comment by Todomir** [comment]
Sorry for the late answer and the bad quality of the gif, but here it illustrates well what I mean: https://imgur.com/a/zWHkElw

**Comment by DoctorFTB** [comment]
What version u use? .12 ?

**Comment by Todomir** [comment]
yep

**Comment by DoctorFTB** [comment]
Try use .13 version. This fixed.

**Comment by Todomir** [comment]
ok, thanks
just a question, I actually had to downgrade for it to work properly and I have just a bunch of cows, if I upgrade now something will happen to them?

**Comment by DoctorFTB** [comment]
I think for ~95% - all ok. 
But anyway u can make backup.

**Comment by Todomir** [comment]
allright, thanks :)
