### ISSUE TITLE
Vertexes of cows can be seen through walls.

### ISSUE THREAD

**Issue by tyler489** [DoctorFTB/FluidCows#7]
Where the top of the cow meets the side of the cow that single strip of pixel will sometimes render through walls.. I think this is probably a forge  bug to be honest.

**Comment by DoctorFTB** [comment]
![image](https://user-images.githubusercontent.com/20482982/51375772-d0a23580-1b17-11e9-903f-6d7131371ff6.png)
You about that?
If true, its minecraft vanilla bug.

**Comment by tyler489** [comment]
No..

**Comment by DoctorFTB** [comment]
Check screen...
Its from vanilla 1.7.10 minecraft with vanilla cow..

**Comment by tyler489** [comment]
https://gyazo.com/aeb80482260db3aceb3b7240f9c1131c

just little lines like that... ones knightslime from tinkers and ones Vivid alloy cow from enderio
also occurs with lava water obsid iron Redstone cows...

**Comment by DoctorFTB** [comment]
I cant recreate.
Could u send recreate methods?

**Comment by tyler489** [comment]
Was Playing Stoneblock 
Had cows in a room with one block of stone wall between the room im in and the cow.

**Comment by DoctorFTB** [comment]
Hmmm.. Sorry, I cant recreate .. And.. Not understand how fix.. Sorry.
